### ISSUE TITLE
Can't extract the data from .ain file

### ISSUE THREAD

**Issue by fcolecumberri** [nunuhara/libsys4#12]
Hi, I am trying to extract the data on a .ain file but when I run:
```sh
alice ain dump -t -o out.txt System39.ain
```
I get:
```
AINI
ERROR: Failed to open ain file: Unrecognized or invalid AIN format
```

I have been tracking the problem and I found out that the file `ain.c` on the line:

https://github.com/nunuhara/libsys4/blob/2ee5013ffd4bdc53c2c02a709bcf3c3ff37ba897/src/ain.c#L1224

is expecting the file to start with `AI2\0\0\0\0` but the file I am trying to use starts with `AINI\1\0\0\0`.
I don't know if this is another version ain version/format.

I wouldn't have problem to program whatever is needed to read it and make a pull request, but I have no Idea about where to start looking for documentation.

It's impressive how all the documentation I have been able to find came from you own haniwa.technology page.

**Comment by nunuhara** [comment]
System 3.9 ain files have a totally different format from System 4 ain files and are not supported by the `alice ain` commands. I recommend using [xsys35c](https://github.com/kichikuou/xsys35c) for working with System 3.x games.

I'm not really interested in adding support for System 3.9 ain files since it would just be replicating what already exists in xsys35c. Thanks for the offer though.

**Comment by fcolecumberri** [comment]
Thanks, then I will use sys35c.
